# Form implementation generated from reading ui file 'robot_log_visualizer/ui/misc/video_tab.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VideoTab(object):
    def setupUi(self, VideoTab):
        VideoTab.setObjectName("VideoTab")
        VideoTab.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VideoTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.webcamView = QVideoWidget(parent=VideoTab)
        self.webcamView.setObjectName("webcamView")
        self.horizontalLayout.addWidget(self.webcamView)

        self.retranslateUi(VideoTab)
        QtCore.QMetaObject.connectSlotsByName(VideoTab)

    def retranslateUi(self, VideoTab):
        _translate = QtCore.QCoreApplication.translate
        VideoTab.setWindowTitle(_translate("VideoTab", "Form"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
